config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: "users", :omniauth_callbacks => "callbacks"},
             :path => '', :path_names => {  edit: 'profile' }

  root 'home#index'

  # git
  get 'git-search-result', to: 'git#index', as: 'search_page'
  get 'git-search', to: 'git#search', as: 'search'

  # git repositories
  get 'repositories', to: 'git#get_user_repositories', as: 'user_repositories'
  get 'new-repository', to: 'git#new_repository', as: 'create_repository'
  post 'create-repository', to: 'git#create_repository'
  delete 'repository', to: 'git#delete_repository'
  get 'favorite-repositories/:user_id', to: 'git#get_user_favorite_repositories', as: 'user_favorite_repositories'
  post 'add-favorite-repository', to: 'git#add_favorite_repository'
  post 'remove-favorite-repository', to: 'git#remove_favorite_repository'


  # api routes
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
          sessions: 'v1/auth',
          registrations: 'v1/registration',
      }
    end
  end

end

app/controllers/git_controller.rb
class GitController < ApplicationController
  before_action :create_repository_params, only: :create_repository
  before_action :delete_repository_params, only: :delete_repository
  before_action :favorite_repository_params, only: [:add_favorite_repository, :remove_favorite_repository]
  before_action :authenticate_user!


  include GitManager
  include Validation

  def index

  end

  def new_repository

  end

  def get_user_repositories
    git = GitManager::GitReader.call(get_git_client)
    repositories = git.get_user_repositories
    render "git/repositories", locals: {repositories: repositories}
  end

  def create_repository
    git = GitManager::GitCreator.call(get_git_client, create_repository_params)
    create_repository = git.create_repository
    create_repository[:success] ? (render json: {success: 1}) : (render json: {error: 1, message: create_repository[:message]})
  end

  def delete_repository
    git = GitManager::GitCreator.call(get_git_client, delete_repository_params)
    delete_repository = git.delete_repository
    delete_repository[:success] ? (render json: {success: 1}) : (render json: {error: 1, message: delete_repository[:message]})
  end

  def search
    git = GitManager::GitReader.call(get_git_client, params)
    repositories = git.search
    render json: repositories
  end

  def get_user_favorite_repositories
    user_id = params[:user_id]
    user_repository_ids = FavoriteRepository.where(user_id: user_id).pluck(:repo_id)
    render json: user_repository_ids
  end

  def add_favorite_repository
    user_id = favorite_repository_params[:user_id]
    repository_id = favorite_repository_params[:repo_id]
    user_repository = FavoriteRepository.where(user_id: user_id, repo_id: repository_id).exists?
    unless user_repository
      current_user.favorite_repositories.create(repo_id: repository_id)
    end

    render json: {success: 1}

  end

  def remove_favorite_repository
    user_id = favorite_repository_params[:user_id]
    repository_id = favorite_repository_params[:repo_id]
    user_repository = FavoriteRepository.where(user_id: user_id, repo_id: repository_id)
    user_repository.destroy_all

    render json: {success: 1}
  end

  private

  def create_repository_params
    begin
      param! :repo_name, String, blank: false, required: true, message: "Repository Name is required"
      param! :repo_name, String, min_length: 5, message: "The Repository Name is too short"
      param! :repo_type, String, in: %w(1 0), required: true, message: "Please select repo type"
      params
    rescue => error
      render json: {
          error: 1,
          message: error.message
      }
    end

  end

  def delete_repository_params
    begin
      param! :repo_name, String, blank: false, required: true, message: "Repository Name is required"
      params
    rescue => error
      render json: {
          error: 1,
          message: error.message
      }
    end
  end


  def favorite_repository_params
    begin
      param! :user_id, Integer, blank: false, required: true, message: "User ID is required"
      param! :repo_id, Integer, blank: false, required: true, message: "Repo ID is required"
      params
    rescue => error
      render json: {
          error: 1,
          message: error.message
      }
    end
  end

end

app/helpers/git_helper.rb
module GitHelper
  def get_git_client
    if has_git_access_token?
      Octokit::Client.new(access_token: current_user.git_access_token)
    end
  end

  def has_git_access_token?
    current_user.git_access_token?
  end
end

app/views/git/index.html.haml
- if has_git_access_token?
  .container
    = stylesheet_link_tag 'git.css', media: 'all', 'data-turbolinks-track': 'reload'
    %form
      .form-group
        %label{:for => "search_repositories"} Search Repositories
        %input#search_repositories.form-control{:name => "search_repositories", :placeholder => "Device", :type => "text"}/
        %input#user_id{:name => "user_id", :type => "hidden", :value => "#{current_user.id}"}/
    #repos_pagination{:style => "display: none"}
      / append html here
    %table.table
      %thead#git_table_head
        %tr
          %th{:scope => "col"} Favorite
          %th{:scope => "col"} ID
          %th{:scope => "col"} Repository Name
          %th{:scope => "col"} Url
          %th{:scope => "col"} Description
      %tbody#git_table_body
    = javascript_include_tag 'github/github', defer: 'defer'
    = javascript_include_tag 'pagination', defer: 'defer'
- else
  .alert.alert-primary.text-center{:role => "alert"}
    Please Set Git Access Token in Profile

app/views/git/new_repository.html.haml
.container
  %form#create_repository{style: "width: 40rem;margin:auto"}
    .alert.alert-danger.d-none#create_repo_error_messages
    .form-group
      %label Repository Name
      %input#exampleInputEmail1.form-control{"aria-describedby" => "repo-name", placeholder: "Enter Your Repository Code", type: "text", name: 'repo_name'}/
    .form-group
      %label Repository Type
      .form-check
        %input#is_private.form-check-input{type: "checkbox", value: "1"}/
        %label.form-check-label{for: "is_private"}
          Private
    %button.btn.btn-primary{type: "submit"} Submit

= javascript_include_tag 'github/github', defer: 'defer'

app/views/git/repositories.html.haml
- if has_git_access_token?
  .container
    = link_to "Create New Repository", create_repository_path, method: :get, :class => 'btn btn-primary mb-2'
    .alert.alert-danger.d-none#repositories_error_messages
    %table.table
      %thead#git_table_head
        %tr
          %th{:scope => "col"} ID
          %th{:scope => "col"} Full Name
          %th{:scope => "col"} URL
          %th{:scope => "col"} Actions
      %tbody#git_table_body
        - repositories.each do |repo|
          %tr{id: repo.id}
            %td= repo.id
            %td= repo.full_name
            %td
              %a{href: repo.html_url, target: '_blank'}=repo.html_url
            %td
              %button.btn.btn-danger.delete_repository_button{type: "button", value: repo.full_name} Delete
= javascript_include_tag 'github/github', defer: 'defer'